---
apiVersion: v1
kind: Service
metadata:
  name: cdi-upload-server-loadbalancer
  namespace: kubevirt
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    cdi.kubevirt.io: cdi-upload-server
  type: LoadBalancer
