---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    name: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16G
  storageClassName: nfs-ssd
  volumeMode: Filesystem
---
# kubectl -n minecraft create secret generic mysecret --dry-run=client --from-literal='rcon-password=(some password)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgCrcF4NAcq9B44J8COIPuSvmypmnnx0T8HAbnFbbqqy+fjdPYxqSRXQ95FRZp/yLZqjHw0Xzx2jIPvC5DkmhIuKHR09ZVqOTXwRsEo5+DMS9PmFiH7B8WVUPuVJ0NEDeuoyZ+3CZXpMVBGTP0zgtmuO4aMwQqZoiO0iSqodIFYxkG/wXIFoz/i765GaID3/TM4mitGTe2iyoqm1/yB+uYeZe1CdoNbMN6076uHGtzJGrXj+mcmCWt6oSqCKaxxGVBEoaJF3ID/iHDKuATAArB6GPGG5bjNA/Str6Hi/GZb0vibJOR3t1J6XE0jaOn8cBX8jICApBwEgilAGL8iVN1iGuEpvSPM5Wqbo3kBUAvALIb01HyAifNZV0y6eh6in8OLaTt+gO627YMUQLF6Z1qwwKZ2LUwvyjdfaVsy2OVONtzIWvlvIenNjQ3RuWtlacwyQPrv59pYFVgT6XjngbfYke/vySfGIz3U/BcpumSo3ya5tCutH0vZWVYRaoYAV/4Y4EhEtemkAoUmlVQcMg2T70JqD+DlqVgIzWgs94zZ0a2DdACivlghisZNxYxa+z5KwcDukfMR+fWppS526USBFJVkZEJZ0xk+NjXd+aWFxaRkC8GEC6bBN/jFCn/Ml3++B5L40uMFMPIMKpu9UYCgbwvb2IxWZzaDpwS8wZQJFe/ynkVnRQAuoogsXGIWurfC+ls0t97seXxc=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: minecraft
