---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    name: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16G
  storageClassName: nfs-ssd
  volumeMode: Filesystem
# kubectl -n minecraft create secret generic minecraft-secret --dry-run=client --from-literal='rcon-password=(some password)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-secret
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgADIBcM8Os4ORVubSGTEF+UAwEmUvhgZcMlq1sy41wVE43ozIXYcBq2hpcvAUk0nL5B9uP9RzKqfH9KbRJoTgwi0YG9T0M/Ffq1LzJbsSVuTwq9zkz/bLoQ0xkpD+bJzrYoi0isZ+eBUBuCuUTWR1hPkKNvdqZ+Ov5GKM6bXZsiaFcoKp+xVyJZa/m9AifHBZWISdZnL5ceLeDG506YQwh1M0/ZgQODAMDxzn0uzdnvIxrLOcIbeDbXSH91vBj+fXg2n+ucCBvseZp1OB0O0+hBcM/1ABsRCZm6ePgindIFdUWDwfAuSO13Rqbftw5ZK71hhLqpoNyl5aS36SX6ov/V8n/z4RPj5ySXyOVhd4cCzD88VbbjwsMZdbg5AtOO8JEtfXGVEfBOEB92VQDwMOD0tNeXjPUUNrINpiZNjtKmDNlRJ8A84+tKS/DuedsfrQSr/QUeGesNvQDaX9hxLp2/pJB/C5a32quxD9pHlMFjMjAva4WlM9FdJOjgRfZZFd9j3ZCX4znfDD3js4caD1KrNIctlbVQVBElGTypFkrcJwWmHhbwmyZMw/ZgVHRUB59E8ztMRBkQjOPDH9pGDV7FWAFBj4DI7SHe0hNNiuTSwgWkb2CeBGZ51Y/JZa8/MzAhylpbMeLwQTrSFSVqLZhB8+ccaWLjDoME9OixjdqRATCYoRAD70H4iwg2QpBR8YvF3nmVNO17jj4=
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-secret
      namespace: minecraft
