---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
  labels:
    name: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16G
  storageClassName: nfs-ssd
  volumeMode: Filesystem
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft
  namespace: minecraft
spec:
  encryptedData:
    rcon-password: AgB7ddbfeGXx4fpGnN47r0hK7OdRdB6PbLZeVXOgq8WD8sosL5mc8/sKo56Gu8/CNbVuvgr/jeswWqqOkopWFTgesMBCdE/BJwZw88NFrAM2FxfW4fUp6iwU+B30vFkLybnWRbm3BSD5h16AWrm/KkZPZA6KVJ+Sc35s1KcuhyXlyK4aNeB7RiFL8IfLLaNmvzY/b3fttEBEo2jm48oA6X3zolAMiTPAO/xh6vrWbGx+gBkU+yZduqp3+jTz2eSFW5NpGu05PN7WWCkorIKgRjBn8j0sbac2gPAoUQm6zp9WNT7YbC/TL1ViArvzw1wSGX9ePaEcwuRhBArs9qRQ+yVz6B7imn0svXc3AO8BJIK3LMm/ZM3IuEieHaqysy8+3nX9fUia97+rtOIYkVWFm8V8n6HF/G9+av0IA/jdp2GrXP7tXja65j0yjkjRtFvPd1ofamZ1czEOwRvptRWdH9HlZmcPoNVn6eW8mbJqpMiAiLUdFa581hLDZIk8SewOH+Kf0zp/UW8OMeK0GqtSXmUMt1GLWzVYPadhXtGLgZgIubTV+69fIW8jImxKneIUX1QNhpU9u7fKOkE/OMC8VHvNxAL23bcp1hLrwvnOcrwYhc5x1r8oZPzetk5ebqrr+2a4Q5oy7SfqwTVRVKkJe8fNmo1b50IFOUIXCXUcEbu81kLnzLe9YRo98vbJRnroW7HBD/k4ki7nlQ==
  template:
    metadata:
      creationTimestamp: null
      name: minecraft
      namespace: minecraft
