---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: minecraft
    name: server
    labels:
        app: server
spec:
    serviceName: minecraft
    replicas: 1
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            affinity:
                nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 1
                          preference:
                              matchExpressions:
                                  - key: kubernetes.io/hostname
                                    operator: In
                                    values:
                                        - bee-1
            volumes:
                - name: shared
                  persistentVolumeClaim:
                      claimName: minecraft
                      readOnly: false
            containers:
                - name: server
                  image: itzg/minecraft-server:2024.12.1-java21-graalvm
                  env:
                      - name: TYPE
                        value: "FABRIC"
                      - name: EULA
                        value: "TRUE"
                      - name: RCON_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: minecraft
                                key: rcon-password
                      - name: MEMORY
                        value: "4G"
                      - name: USE_AIKAR_FLAGS
                        value: "true"
                      - name: TUNE_VIRTUALIZED
                        value: "TRUE"
                      - name: TUNE_NURSERY_SIZES
                        value: "TRUE"
                      - name: VERSION
                        value: "1.21.4"
                  volumeMounts:
                      - name: shared
                        subPath: minecraft/data
                        mountPath: /data
                  ports:
                      - containerPort: 25565
                        protocol: TCP
                      - containerPort: 25565
                        protocol: UDP
                      - containerPort: 25575
                        protocol: TCP
                  tty: true
                  stdin: true
---
apiVersion: v1
kind: Service
metadata:
    name: server
    namespace: minecraft
spec:
    selector:
        app: server
    ports:
        - name: port-1
          protocol: TCP
          port: 25565
          targetPort: 25565
        - name: port-2
          protocol: TCP
          port: 25575
          targetPort: 25575
        - name: port-3
          protocol: UDP
          port: 25565
          targetPort: 25565
    type: LoadBalancer
