# this middleware is for specifically the VictoriaLogs server- it has no password, so we want to protect it
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: monitoring
  name: victorialogs-whitelist
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8 # internal IP range
      - 172.16.0.0/12 # internal IP range
      - 192.168.0.0/16 # internal IP range
      - 100.64.0.0/10 # Tailscale VPN
