apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parca
  namespace: argo-cd
spec:
  destination:
    namespace: parca
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
  sources:
    - path: applications/parca
      repoURL: https://github.com/initialed85/home-ops
      targetRevision: HEAD
