apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argo-cd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - chart: prometheus-operator-crds
      targetRevision: 15.0.0
      repoURL: https://prometheus-community.github.io/helm-charts
      helm:
        releaseName: prometheus-operator-crds
