---
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: mqtt-things
    name: sensors-cli
data:
    MQTT_BROKER_HOST: "192.168.137.251"
    BRIDGE_HOST: "192.168.137.252"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    namespace: mqtt-things
    name: sensors-cli
    labels:
        app: sensors-cli
spec:
    serviceName: sensors-cli
    replicas: 1
    selector:
        matchLabels:
            app: sensors-cli
    template:
        metadata:
            labels:
                app: sensors-cli
        spec:
            nodeSelector:
                kubernetes.io/arch: amd64
            hostNetwork: true
            containers:
                - name: sensors-cli
                  image: initialed85/mqtt-things-sensors-cli:latest
                  imagePullPolicy: Always
                  env:
                      - name: MQTT_CLIENT_PROVIDER
                        value: gmq
                      - name: MQTT_BROKER_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: sensors-cli
                                key: MQTT_BROKER_HOST
                      - name: API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: mqtt-things
                                key: hue-api-key
                      - name: BRIDGE_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: sensors-cli
                                key: BRIDGE_HOST
                  resources: {}
                  command:
                      [
                          "/srv/entrypoint",
                          "-host",
                          "$(MQTT_BROKER_HOST)",
                          "-apiKey",
                          "$(API_KEY)",
                          "-bridgeHost",
                          "$(BRIDGE_HOST)",
                      ]
