---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-registry
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: edward@wevolt.com.au
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: kube-registry
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: edward@wevolt.com.au
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
