---
apiVersion: v1
kind: Namespace
metadata:
    name: public
    labels:
        name: public
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: public
    namespace: public
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1G
    storageClassName: nfs-ssd
    volumeMode: Filesystem
