---
apiVersion: v1
kind: Service
metadata:
  name: whatever-ed-is-working-on
spec:
  selector:
    app: whatever-ed-is-working-on
  ports:
    - name: whatever-ed-is-working-on
      port: 3000
      targetPort: 3000
