---
apiVersion: v1
kind: Service
metadata:
  name: whatever-ed-is-working-on
  namespace: whatever-ed-is-working-on
  labels:
    monitoring: "true"
spec:
  selector:
    app: whatever-ed-is-working-on
  type: ClusterIP
  clusterIP: None # headless service
  ports:
    - name: port-1
      port: 3000
      targetPort: 3000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: whatever-ed-is-working-on
  namespace: whatever-ed-is-working-on
  labels:
    kubernetes.io/service-name: whatever-ed-is-working-on
addressType: IPv4
ports:
  - name: port-1
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - "192.168.137.222"
    conditions: {}
