---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: kube-system
  name: hubble-ui-whitelist
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8 # internal IP range
      - 172.16.0.0/12 # internal IP range
      - 192.168.0.0/16 # internal IP range
      - 100.64.0.0/10 # Tailscale VPN
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-hubble-ui-whitelist@kubernetescrd
  name: hubble-ui
  namespace: kube-system
spec:
  ingressClassName: traefik
  rules:
    - host: hubble-ui.initialed85.cc
      http:
        paths:
          - backend:
              service:
                name: hubble-ui
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - hubble-ui.initialed85.cc
      secretName: hubble-ui-ingress-tls
