apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: topic-exporter-cli
  namespace: monitoring
  # labels:
  #   prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - topic-exporter-cli.mqtt-things.svc.cluster.local:9137
