---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived
  namespace: kube-system
data:
  ocnus.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state MASTER
        virtual_router_id 51
        priority 100
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            # 192.168.137.34
            192.168.137.30
            192.168.137.27
            192.168.137.28
            192.168.137.29
            192.168.137.253
            192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  adonis.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 99
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            # 192.168.137.30
            192.168.137.27
            192.168.137.28
            192.168.137.29
            192.168.137.253
            192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  dionysus.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 97
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            192.168.137.30
            192.168.137.27
            # 192.168.137.28
            192.168.137.29
            192.168.137.253
            192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  chronos.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 98
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            192.168.137.30
            # 192.168.137.27
            192.168.137.28
            192.168.137.29
            192.168.137.253
            192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  hera.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 96
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            192.168.137.30
            192.168.137.27
            192.168.137.28
            # 192.168.137.29
            192.168.137.253
            192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  romulus.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 95
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            192.168.137.30
            192.168.137.27
            192.168.137.28
            192.168.137.29
            # 192.168.137.253
            192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  bee-1.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 95
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            192.168.137.30
            192.168.137.27
            192.168.137.28
            192.168.137.29
            192.168.137.253
            # 192.168.137.35
            192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  bee-2.conf: |
    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 95
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
            192.168.137.34
            192.168.137.30
            192.168.137.27
            192.168.137.28
            192.168.137.29
            192.168.137.253
            192.168.137.35
            # 192.168.137.36
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
