---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived
  namespace: kube-system
data:
  adonis.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 99
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          # 192.168.137.30  # adonis
          192.168.137.35  # bee-1
          192.168.137.36  # bee-2
          192.168.137.37  # beefcake-1
          192.168.137.27  # chronos
          192.168.137.28  # dionysus
          192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  bee-1.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 102
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          192.168.137.30  # adonis
          # 192.168.137.35  # bee-1
          192.168.137.36  # bee-2
          192.168.137.37  # beefcake-1
          192.168.137.27  # chronos
          192.168.137.28  # dionysus
          192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  bee-2.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 101
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          192.168.137.30  # adonis
          192.168.137.35  # bee-1
          # 192.168.137.36  # bee-2
          192.168.137.37  # beefcake-1
          192.168.137.27  # chronos
          192.168.137.28  # dionysus
          192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  beefcake-1.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 101
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          192.168.137.30  # adonis
          192.168.137.35  # bee-1
          192.168.137.36  # bee-2
          # 192.168.137.37  # beefcake-1
          192.168.137.27  # chronos
          192.168.137.28  # dionysus
          192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  chronos.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 98
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          192.168.137.30  # adonis
          192.168.137.35  # bee-1
          192.168.137.36  # bee-2
          192.168.137.37  # beefcake-1
          # 192.168.137.27  # chronos
          192.168.137.28  # dionysus
          192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  dionysus.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 97
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          192.168.137.30  # adonis
          192.168.137.35  # bee-1
          192.168.137.36  # bee-2
          192.168.137.37  # beefcake-1
          192.168.137.27  # chronos
          # 192.168.137.28  # dionysus
          192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
  romulus.conf: |
    global_defs {
        script_user root
        enable_script_security
    }

    vrrp_instance VI_1 {
        interface eth0
        state BACKUP
        virtual_router_id 51
        priority 95
        advert_int 1
        use_vmac
        vmac_xmit_base
        authentication {
            auth_type PASS
            auth_pass Password1
        }
        unicast_peer {
          192.168.137.30  # adonis
          192.168.137.35  # bee-1
          192.168.137.36  # bee-2
          192.168.137.37  # beefcake-1
          192.168.137.27  # chronos
          192.168.137.28  # dionysus
          # 192.168.137.253 # romulus
        }
        virtual_ipaddress {
            192.168.137.10
        }
    }
