apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: kube-system
  labels:
    app: keepalived
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      hostNetwork: true
      volumes:
        - name: etc-keepalived
          configMap:
            name: keepalived
      containers:
        - name: keepalived
          image: kube-registry:5000/keepalived
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - name: etc-keepalived
              mountPath: /etc/keepalived
