---
apiVersion: v1
kind: Namespace
metadata:
  name: camry
  labels:
    name: camry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd
  namespace: camry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  storageClassName: nfs-hdd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd
  namespace: camry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Gi
  storageClassName: nfs-ssd
  volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: camry
data:
  API_URL: http://api:7070
  BASE_URL: /
  DESTINATION_URL: rtsp://mediamtx:8554/streams
  DJANGOLANG_NODE_NAME: api
  DJANGOLANG_PROFILE: "0"
  ENABLE_PASSTHROUGH: "1"
  MTX_PROTOCOLS: tcp
  MTX_WEBRTCADDITIONALHOSTS: camry.initialed85.cc
  PAGER: "cat"
  POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
  POSTGRES_DB: camry
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  REDIS_URL: redis://redis:6379
  SWAGGER_JSON_URL: https://camry.initialed85.cc/api/openapi.json
---
# kubectl -n camry create secret generic secret --dry-run=client --from-literal='POSTGRES_PASSWORD=(redacted)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: camry
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAZHKmL5lUL/IHbF4WuyR4kClAYn4r0gOPoeU8vq0KSyLIiL3S0hlpu3AJ0HFDOtNATFr9EaMrQSHHzBGZSPME41OdZkxkmAmTU810GpaQpJtSwDYMTCKzVjETpPjb2pWqBeBWQfCH7c46jcDgDkKfmtSsDvXKa6KmrHXy3zxS2HRdl4ykFewm/jvSFr3lDe5J1tMUptxXwYc16vUjQ8n1/NzLp9hHDN2DiTvHzRjuoZaolN54mKa3wKDhfokYJCi1jkJ9qSzdVkP4x/+Bxq/4pB6clhKIKM07OC+YeOx48nj25fuZ3tJW1mVpCjsB3hPO4NTD/Yh7e/OCftGmiOtZKxgFr6xpQV5OXBKgU7GGZsStrWbDJt//Sv/sLCOT6vVdEHv+5C9LD/dw80iKOkMHEQZJq+4qav+wIBzg+U+ZS58OfybxC/O6ULsHy6WPAMxnZecljyowrEiyO0cnHjB/uSbEh4PKs1q6AyKov5IGn5ctbEIuhw2PEeeqD5NPgGYQEpncjX23CyZR3XZK+uNT6McVScq/Uhm1EKcrqOjoQMd4HNioWEl9XYxgJNtqkj677pGwl9cpeWQG5Fc01WdwOMMR1W7QzfreHY2NSUiXOMu3TlkC3FXT4NUpw7jOm6kGf4/pE58dGPghrwMS1YnLTCY9++4hJOrgZHYKEmkIgmq3c3LESiIJ82nG12hF7oPPcAXKSt6xGHw==
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: camry
