---
apiVersion: v1
kind: Namespace
metadata:
  name: camry
  labels:
    name: camry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdd
  namespace: camry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2T
  storageClassName: nfs-hdd
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd
  namespace: camry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Gi
  storageClassName: nfs-ssd
  volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: camry
data:
  API_URL: http://api:7070
  BASE_URL: /
  DESTINATION_URL: rtsp://mediamtx:8554/streams
  DJANGOLANG_NODE_NAME: api
  DJANGOLANG_PROFILE: "0"
  ENABLE_PASSTHROUGH: "1"
  MTX_PROTOCOLS: tcp
  MTX_WEBRTCADDITIONALHOSTS: camry.initialed85.cc
  PAGER: "cat"
  POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
  POSTGRES_DB: camry
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  REDIS_URL: redis://redis:6379
  SWAGGER_JSON_URL: https://camry.initialed85.cc/api/openapi.json
---
# kubectl -n camry create secret generic secret --dry-run=client --from-literal='POSTGRES_PASSWORD=(redacted)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: secret
#   namespace: camry
# spec:
#   encryptedData:
#     POSTGRES_PASSWORD: AgCpO92getu8+hm8s1oUtfx0WvgGagAIHQxL+ty5Lw8KcQhiekDJH+XV12PU1B2K2nKZcYg5OWApFl/azWW9Yllnk+HxPerZa15H0vwD9+f4FQULEP1az4wF3cRB2xR6lVZD8aKXIw2S61E7UyHkVOZ+xFYs4wHo+pgi5aS5qvB2CwrAmoYW8rxD2WZeZqm5uxOeKye7/R5z38jaU9zgo5sPS4Jx/npNGonZFQw7BbNEpPIWi47qzr8vtz4sRlZdSqyitLc70NPi13mR9j3sqH04Ptf1swywcv0FHUME+ZDgiqi+3FxhzKTGZdIqpLAUUFf6fURspIPosanbx/8Qn/hbiDDcP+KGRzIubDZG51E5BVJHmmHhPg5rootKhcqEpNn7Rx8pBXsv+IRREVTtPO7LPxcXmKMDuYMtFVJYOFfNrB3LYyEwnlMiPD4S9j7uIED8OwbXgNKdVZhbUtwau4DIlm1QKCHDfmQJjHPUw7mzH6jaKw9nEnDumVigtqreGatLUVXlS75lQ1nz2ElxPIJv0kL1qNveHcQPNNXUrrV3q0bhmuGV1U70U60ZWRjVdPwsYA09oIoFkvGVVZ5lrfNo6pUnQ/3+7uLoxFGoAJnO0iKZAdyYrjA6I9UB2BFqPJzMsXhO3iteCGV33rhdLL+CHm8Ui8tdLRzxnfrBBE5S+RX/tddb72M+dM9Qx+AfLGaAXJz3FrhRmw==
#   template:
#     metadata:
#       creationTimestamp: null
#       name: secret
#       namespace: camry
