---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: camry
  name: home-assistant-webhook-front-door
  labels:
    app: home-assistant-webhook-front-door
    service: home-assistant-webhook
    system: camry
spec:
  serviceName: home-assistant-webhook-front-door
  replicas: 0
  selector:
    matchLabels:
      app: home-assistant-webhook-front-door
      service: home-assistant-webhook
  template:
    metadata:
      labels:
        app: home-assistant-webhook-front-door
        service: home-assistant-webhook
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: home-assistant-webhook
          image: kube-registry:5000/camry-home-assistant-webhook:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          env:
            - name: DEBUG
              value: "0"
            - name: CAMERA_ID
              value: ecf45b06-d641-426e-bcbf-86919be7840a
            - name: CLASS_NAME
              value: person
            - name: WEBHOOK_SUFFIX
              value: front-door
            - name: POSTGRES_PORT
              value: "5432"
