---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: camry
  name: home-assistant-webhook-driveway
  labels:
    app: home-assistant-webhook-driveway
    service: home-assistant-webhook
    system: camry
spec:
  serviceName: home-assistant-webhook-driveway
  replicas: 0
  selector:
    matchLabels:
      app: home-assistant-webhook-driveway
      service: home-assistant-webhook
  template:
    metadata:
      labels:
        app: home-assistant-webhook-driveway
        service: home-assistant-webhook
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: home-assistant-webhook
          image: kube-registry:5000/camry-home-assistant-webhook:latest
          imagePullPolicy: Always
          stdin: true
          tty: true
          env:
            - name: DEBUG
              value: "0"
            - name: CAMERA_ID
              value: a37a2206-a5e7-4547-90c5-d9220ba3d992
            - name: CLASS_NAME
              value: person
            - name: WEBHOOK_SUFFIX
              value: driveway
            - name: POSTGRES_PORT
              value: "5432"
