---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prune
  namespace: camry
data:
  prune.sql: |
    SET
        session_replication_role = replica;

    DELETE FROM detection
    WHERE
        created_at < now() - interval '7 days';

    DELETE FROM video
    WHERE
        created_at < now() - interval '7 days';

    UPDATE detection
    SET
        updated_at = now()
    WHERE
        id = (
            SELECT
                id
            FROM
                detection
            ORDER BY
                created_at DESC
            LIMIT
                1
        );

    UPDATE video
    SET
        updated_at = now()
    WHERE
        id = (
            SELECT
                id
            FROM
                video
            ORDER BY
                created_at DESC
            LIMIT
                1
        );

    UPDATE camera
    SET
        updated_at = now()
    WHERE
        id = (
            SELECT
                id
            FROM
                camera
            ORDER BY
                created_at DESC
            LIMIT
                1
        );

    VACUUM FULL
    ANALYZE;
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: prune
  namespace: camry
  labels:
    app: prune
    service: prune
    system: camry
spec:
  concurrencyPolicy: Forbid
  schedule: "30 1 * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: prune
              configMap:
                name: prune
            - name: hdd
              persistentVolumeClaim:
                claimName: hdd
                readOnly: false
          containers:
            - name: prune
              image: ubuntu:22.04
              volumeMounts:
                - name: hdd
                  subPath: media
                  mountPath: /srv/media
              command:
                - "bash"
                - "-c"
                - "cd /srv/media && find . -maxdepth 1 -mtime +7 -type f -delete"
            - name: postgres
              image: postgis/postgis:16-3.4
              volumeMounts:
                - name: prune
                  subPath: prune.sql
                  mountPath: /tmp/prune.sql
              env:
                - name: PAGER
                  value: CAT
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: secret
                      key: POSTGRES_PASSWORD
              command:
                - "psql"
                - "-h"
                - "postgres"
                - "-p"
                - "5432"
                - "-U"
                - "postgres"
                - "camry"
                - "-f"
                - "/tmp/prune.sql"
