---
# kubectl -n scanner create secret generic --type kubernetes.io/basic-auth scanner-basic-auth --dry-run=client --from-literal='username=(redacted)' --from-literal='password=(redacted)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scanner-basic-auth
  namespace: scanner
spec:
  encryptedData:
    password: AgDJ9k4P+MHHoVj3No+i0EsXVMNjJkuljQXuJsJFzT8IiRtiwkDKdRG0DLVguHnEaRBSMgaAsX/DxzzzDG226FvgCo6SOrpSosGhhJ7jOIwSBS0jfiv8kkW9r6HHSzb7sGs6KRTTtxjAgqfVyfa5a52OsHdEp4vnbaxXUu+gtBzvypVriPI+MAcVHUCk9n1EWPF/OYZIQUo8hpTtvIHkO26DDFYt4Q/qDD3lR5IiFGoeHV303yn/m9OwbU55Azcl8xTIu1+IeFPrglrYqj/2TQPm6D+h3btgrdQM0jNCm226tWNiFBaERpbdCrb9lEGLy2h2mFAw0dR7B9geMfd5x7FxVFZGNLrcxAwsrJW6fQP6nWfYWtaDcWHumi0paRADUUSWQFgYFskBvD5B+zAKc+1TpuPiVNGhH473nH1jmXxF0HaJ2iqQirjRMGv8HipPL4ReCmkvs/3TnQ905WQwKovJX4uX3HmMh8eS8g8OYGAof9zA++EAuP4QvU1fu9Jgny7wCoqdxa2lYJEHWTOiQz8S14JHDvBV2CJAsGL7/hJG01Td73aEm9BzNDKMY0KOhj2Vc7tFIq4RoPOeFLRPX9cJ6KM2j2r1dBT6pesDQ5hTFZs5bIFiCjdOn606jC57d4hcPYztEge5cwnMaDRb7O1KtP+OkFmQhTNIqVEXozuDO9rFc+yuClq59bEXC2QMjMleEA2tdFSTCXvrnawz
    username: AgAKybUvw08XlP/5QfQRNfVqnjzkogzkAcSnQcp4cGD+4/jHlz6ZOSkrneXUyp0VHAcxP9aDLOIMFRccouc8IR2dw9+6J2uQnjkP+4IdjPlrRVokWIq0FVJ+oCn1YZ34tdbxrjr5c3imgz0k5khpGJNs8NQpUg1vKsuyOKONHUOM72iBN/HeL9HQIzA/pKkO5bIg4N8Se5sDpH3rgn2XLfKvY3ckxDS0R7hVHA8nbLzRjgRjKKoYV7Gzwrat9MUnnAmbPKHu4C7AdtYMDRf7K3iBRa05SBpJr54tLqBzNxlvZnP+5xkCWJrVoelQfpxMXqGKplhjgU3O1EWbv4VNnIiauO/WebKE9aVMYozJB3s28r19zAk/ctoBRO9hos+HZA7tkNU5IWMYGBL1+8eUeGXC/OeoRkM5/qz2WEx3Pgs9YVNgfVsCX/iBKu+QFrrcl2nRqrcMR+ESF+G3avNncpZIqY79vHKPjJplQEixJPvFqnwK6LVt0rpk6FueIdiWUfcVuhqSk4D5FEe64bspyAykWzjDydJ7FxVlyygCly/UOh/zKJarpPtn/M0aHFDRM1BkrxJo8D6yUxBGrgEkfWORRxscJkaPkB6X0leOrKUFzBKcRMztulJnOkMUg6lCjWKfV16VyPkQRFspnTGYFHCqyQgiCqGOkfzZPuIWpNSUHJEwDPXxwGgZJiHLsoLHvXpDTlEMl21n
  template:
    metadata:
      name: scanner-basic-auth
      namespace: scanner
    type: kubernetes.io/basic-auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: scanner
  name: scanner-basic-auth
spec:
  basicAuth:
    secret: scanner-basic-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: scanner
  name: scanner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: scanner-scanner-basic-auth@kubernetescrd # (namespace)-(name)@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - scanner.initialed85.cc
      secretName: scanner
  rules:
    - host: scanner.initialed85.cc
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nginx
                port:
                  number: 80
          - pathType: Prefix
            path: /filebrowser
            backend:
              service:
                name: filebrowser
                port:
                  number: 8080
