---
apiVersion: v1
kind: Namespace
metadata:
  name: fred
  labels:
    name: fred
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd
  namespace: fred
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-ssd
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: local
#   namespace: fred
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 128Gi
#   storageClassName: local-path
#   volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: fred
data:
  API_URL: http://api:7070
  BASE_URL: /
  DJANGOLANG_NODE_NAME: api
  DJANGOLANG_PROFILE: "1"
  PAGER: "cat"
  POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
  POSTGRES_DB: fred
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  REDIS_URL: redis://redis:6379
  SWAGGER_JSON_URL: https://fred.initialed85.cc/api/openapi.json
  daemon.json: |
    {
      "insecure-registries": [
        "kube-registry:5000",
        "kube-registry.kube-system.svc.cluster.local:5000"
      ],
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ],
      "default-ulimits": {
        "nofile": {
          "Hard": 128000,
          "Name": "nofile",
          "Soft": 128000
        }
      }
    }
---
# kubectl -n fred create secret generic secret --dry-run=client --from-literal='POSTGRES_PASSWORD=(redacted)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: fred
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC23Cd0h+frdajgtPeWRBH9rXU3bNIpNe5i4KNMVRPEupfkIvpY/VG+quit2J+FXTzXXNeGzD/FQF3Z2hxjzMpafpsEDKxMfOmHa7mDVGVeoWzdyUN+IwAcupLrBhON9nNfvCGyEH08/pVdqmcUmaSRm44vKPRPrjpHkr9ci9JYCyo9ntjaMfJDHov06WOgC2WFaaFAOQpEGMOGYyHc1zZa24IIk7ndP9nKONRxbL1SjG2Vr1lvu9KQjLSJdxIpNsM+6d+FPD6CxVsqbBNM4FFLr6DXQvUY/QLGaBXXVXwyFR4j927z/tDE4UERuyUM5tfzWN0rFVPH3GgpEv6T4NXhzdjgsSv7DeXY7uH7i4712PjlLQZt21Vn8E64aXpkARtxM31+6cn163WqvyimMDAJ45LYdbfwzzjMr21QHnaV1FzG1uHlZCKiXHadPkkjB8vKfW+g6v9PeqpDwkwS6VQ3V1HejhNRUn8SIvIb/g9m9dmlGM/KtvcBsiPC+RbfMxe7tMCmWY8yL5DgatRBdxE4nGEPDSlRUc7TzeuJVTuVXW8TAn+r647uUxENNwuS1iaEp4nHj8ZLuSpwhjZzeSMpTwzZGYBMusa/rUc4H/VA5DqkbvbNAxyzaoP/sfNUcvqw5qGkH5iech7lLdScgNJIz0KIIRdbyZ9PC4cKx8MxG1drkOyPL3xQADnBOCxTEMjZQExMMKEE
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: fred
