---
apiVersion: v1
kind: Namespace
metadata:
  name: fred
  labels:
    name: fred
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd
  namespace: fred
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-ssd
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: local
#   namespace: fred
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 128Gi
#   storageClassName: local-path
#   volumeMode: Filesystem
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: fred
data:
  API_URL: http://api:7070
  BASE_URL: /
  DJANGOLANG_NODE_NAME: api
  DJANGOLANG_PROFILE: "1"
  PAGER: "cat"
  POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
  POSTGRES_DB: fred
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  REDIS_URL: redis://redis:6379
  SWAGGER_JSON_URL: https://fred.initialed85.cc/api/openapi.json
  daemon.json: |
    {
      "insecure-registries": [
        "kube-registry:5000",
        "kube-registry.kube-system.svc.cluster.local:5000"
      ],
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ],
      "default-ulimits": {
        "nofile": {
          "Hard": 128000,
          "Name": "nofile",
          "Soft": 128000
        }
      }
    }
---
# kubectl -n fred create secret generic secret --dry-run=client --from-literal='POSTGRES_PASSWORD=(redacted)' -o yaml | kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: fred
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDJC+yWyUJqta5LxxG54uOQq2bjC3OofvM2Gw2XdVW8NB23zpPXcWvpV6QUtIUNU6+FQAcbSV6PgdlPyOYLZogAs2LG7zA7a5WtoYxkSwc3ZNphZA/W1O/0DgzwnlVkTj4KJ3OLJeJxt+a1xuOoaVhDUE7KJgp2obYlzLMIUcNCKzPiKysMwQJpRLyLJ1zEUQNrvqPqpCyt//DwhXTkdTYtOt3oZmI23lcV6rKD6ptR6l5oVeHOV7oFplcmpQVhtl8t6sp6aUiW9cKVHHj/2BUSbEE5I5g5OBxPx/JkREX86/n5PEyLQsvXETldK7Yj7DUSrMwciV5IS38zEXWPIMnmqpxyJnzNs/H+Z3t1st9vgivvF1f+Gc8+4pr4as1Aw+BmM3PISLa+QGcBuswlMfZx328ldIqrBeM8rBuHhSkeTTS1sUo/T5kOPx152yRIXxXVEFNr+PF1aG9/oUxT5kcDYtnLd33zzcLpU0AKWBwMV6FztKkoIU/eMj/R851vpQ3c6/NPz70/TGSSPHjHYsrLNLw/4weBSY0qzKdGq+fMJ0JJQA6Eh54nGy3oSbGrlrbyo5PCzCUIYSTsPiaDG+6QT7F3F+gvh047JCY8V4sctO2pNVJ/xnkY/Plk9jYUwnV6kJPmRJ50s+PMSfK3eTyGNC8rAU+17Gcfg5t4zM81v4xC8T4z2gJSFoo4wtTDMGLCoeCGF3us
  template:
    metadata:
      name: secret
      namespace: fred
