apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: game-of-life
    name: server
    labels:
        app: server
spec:
    replicas: 0
    selector:
        matchLabels:
            app: server
    template:
        metadata:
            labels:
                app: server
        spec:
            nodeSelector:
                kubernetes.io/arch: amd64
            containers:
                - name: server
                  image: kube-registry:5000/game-of-life:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: server
    namespace: game-of-life
spec:
    selector:
        app: server
    ports:
        - name: server
          port: 80
          targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: game-of-life
    name: server
    labels:
        monitoring: "true"
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt
spec:
    ingressClassName: traefik
    tls:
        - hosts:
              - game-of-life.initialed85.cc
          secretName: server
    rules:
        - host: game-of-life.initialed85.cc
          http:
              paths:
                  - pathType: Prefix
                    path: /
                    backend:
                        service:
                            name: server
                            port:
                                number: 80
