---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-tls-certificate-rsa
  namespace: docker-mailserver
spec:
  secretName: mail-tls-certificate-rsa
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames: [mail.initialed85.cc]
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
