---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: kube-system
data:
  haproxy.cfg: |
    global
      log /dev/log	local0
      log /dev/log	local1 notice
      chroot /var/lib/haproxy
      stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
      stats timeout 30s
      user root
      group root

      # Default SSL material locations
      ca-base /etc/ssl/certs
      crt-base /etc/ssl/private

      # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
            ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
            ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
            ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

    defaults
      log	global
      mode	http
      option	httplog
      option	dontlognull
            timeout connect 5000
            timeout client  50000
            timeout server  50000
      errorfile 400 /etc/haproxy/errors/400.http
      errorfile 403 /etc/haproxy/errors/403.http
      errorfile 408 /etc/haproxy/errors/408.http
      errorfile 500 /etc/haproxy/errors/500.http
      errorfile 502 /etc/haproxy/errors/502.http
      errorfile 503 /etc/haproxy/errors/503.http
      errorfile 504 /etc/haproxy/errors/504.http

    frontend k3s-frontend
        bind *:80
        mode tcp
        option tcplog
        default_backend k3s-backend

    backend k3s-backend
        mode tcp
        balance roundrobin
        # server ocnus    192.168.137.34:79  check send-proxy-v2
        server adonis     192.168.137.30:79  check send-proxy-v2
        server chronos    192.168.137.27:79  check send-proxy-v2
        server dionysus   192.168.137.28:79  check send-proxy-v2
        # server hera     192.168.137.29:79  check send-proxy-v2
        server romulus    192.168.137.253:79 check send-proxy-v2
        server bee-1      192.168.137.35:79  check send-proxy-v2
        server bee-2      192.168.137.35:79  check send-proxy-v2
        server beefcake-1 192.168.137.37:79  check send-proxy-v2

    frontend k3s-frontend-ssl
        bind *:443
        mode tcp
        option tcplog
        default_backend k3s-backend-ssl

    backend k3s-backend-ssl
        mode tcp
        balance roundrobin
        # server ocnus    192.168.137.34:442  check send-proxy-v2
        server adonis     192.168.137.30:442  check send-proxy-v2
        server chronos    192.168.137.27:442  check send-proxy-v2
        server dionysus   192.168.137.28:442  check send-proxy-v2
        # server hera     192.168.137.29:442  check send-proxy-v2
        server romulus    192.168.137.253:442 check send-proxy-v2
        server bee-1      192.168.137.35:442  check send-proxy-v2
        server bee-2      192.168.137.36:442  check send-proxy-v2
        server beefcake-1 192.168.137.36:442  check send-proxy-v2
