---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-in-docker
  namespace: docker-swarm
data:
  daemon.json: |
    {
      "insecure-registries": [
        "http://kube-registry:5000",
        "http://kube-registry.kube-system.svc.cluster.local:5000"
      ],
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ]
    }
